version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./app:/app  
    ports:
      - "8000:8000"  
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
